- name: Check that Oh My ZSH is installed
  stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh_result

- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "~/.oh-my-zsh"
  when: not ohmyzsh_result.stat.exists

- name: "Create a default ZSH configuration"
  template:
    src: templates/.zshrc
    dest: "~/.zshrc"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Check that Auto Suggestions is installed
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: auto_suggestions_result

- name: Install Auto Suggestions
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  when: not auto_suggestions_result.stat.exists
  
- user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes

- name: Create bin folder
  ansible.builtin.file:
    path: ~/.local/bin
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0770'     
    state: directory   

- name: Configure Gitlab SSH Key
  ansible.builtin.command: pwsh -f ./scripts/configure-gitlab-ssh.ps1 "{{ gltoken }}"

- name: Configure Github SSH Key
  ansible.builtin.command: pwsh -f ./scripts/configure-github-ssh.ps1 "{{ ghtoken }}"