---
- hosts: localhost
  become: no
  vars_prompt:

  - name: gltoken
    prompt: What is your Gitlab personall Access Token?
    private: yes

  - name: ghtoken
    prompt: What is your Github personall Access Token?
    private: yes

  roles:
    - packages
    - profile


