- name: add apt repository key
  apt_key:
    url: "{{ item }}"
  with_items: "{{ apt_keys }}"
  become: yes

- name: add apt repository
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repo }}"
  become: yes

- name: Upgrade Packages
  package:
    update_cache: yes
    upgrade: safe 
  become: yes

- name: Install Packages
  apt:
    state: latest
    update_cache: yes
    pkg: "{{ required_packages }}"
  become: yes
